pub struct ListPathOptions {
    pub id: String,
    pub bucket: String,
    pub base_dir: String,
    pub prefix: String,
    pub filter_prefix: String,
    pub marker: String,
    pub limit: usize,
    pub ask_disks: usize,
    pub include_deleted: bool,
    pub recursive: bool,
    pub separator: String,
    pub create: bool,
    pub current_cycle: u64,
    pub oldest_cycle: u64,
    pub include_directories: bool,
    pub transient: bool,
    discard_result: bool,
}
